### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lelegogo26** [BurhanUlTayyab/DetectGPT#4]
执行  python local_infer.py
Please enter your sentence: (Press Enter twice to start processing)
输入 hello word.
报错
raise PipelineException(
transformers.pipelines.base.PipelineException: No mask_token ([MASK]) found on the input

**Comment by lelegogo26** [comment]
python local_infer.py

**Comment by NCwork** [comment]
I think this happens because I did not take in account chinese characters when I selected all text.
I will that this in to account in the future

**Comment by pottergxy** [comment]
Hi, thanks for your amazing app.
I have an issue. When  I input "hello world" in the cmd(win11), there are some errors:
Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\DetectGPT-main\DetectGPT-main\local_infer.py", line 24, in <module>
    model(sentence, 100, "v1.1")
  File "C:\Users\XXX\Downloads\DetectGPT-main\DetectGPT-main\model.py", line 99, in __call__
    return self.call_1_1(sentence, args[1])
  File "C:\Users\XXX\Downloads\DetectGPT-main\DetectGPT-main\model.py", line 264, in call_1_1
    mean_score = sum(scores)/len(scores)
ZeroDivisionError: division by zero
